### ISSUE TITLE
Palettes colors ought to be a list RGB triplets

### ISSUE THREAD

**Issue by Ragzouken** [Ragzouken/npm-bitsy-parser#3]
The reason they are just integers right now was at the time this seemed like the fundamental primitive for color, but after running into endianness issues it seems like a mistake. Since you can't necessarily write those color integers directly into ImageData buffers without working out endianness, I think there's no upside to the integers and RGB would be a lot more direct and easy to work with.

@seleb any objections?

**Comment by seleb** [comment]
makes sense to me; just remember to do a major version bump since it'd be a breaking change
